name: tool_base
description: Base for developing command line apps. Take from Flutter Tools.
version: 2.0.0
homepage: https://github.com/mmcc007/tool_base

environment:
  sdk: '>=3.0.0'

dependencies:
  archive: ^3.1.2
  file: ^7.0.0
  intl: ^0.18.1
#  platform: ^2.2.0
  process: ^5.0.2
  pub_cache: ^0.3.1

dev_dependencies:
  build_runner: ^2.0.0
  file_testing: ^3.0.0
  lints: ^1.0.1
  mockito: ^5.0.16
  quiver: ^3.0.0
  test: ^1.19.2
